"""empty message

Revision ID: e12f878ffa3d
Revises: 795023c5ed78
Create Date: 2023-07-05 17:07:16.200800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e12f878ffa3d'
down_revision = '795023c5ed78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(), nullable=True))
        batch_op.drop_column('contactInfo')
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('firstname', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('lastname', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('contactInfo', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('password')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
